*************************************************************************************************************;
*  Project Name :           PJK/PJF Analysis				 												*
*  Principal Investigator : OZTURK/GHENBOT																	*
*  Name of Program :        SUVIVAL_GUEST_LECTURE_ANALYSIS.sas												*
*  Programmer :             Jonathan Heintz                                                                 *
*  Start Date :             March 27th, 2025	                	                                        *
*  Related programs : 		C:\Users\jrheintz\Desktop\SURVIVAL_LECTURE_SIMULATION_CREATION.sas				*
*  Data Used:	   	  		C:\Users\jrheintz\Desktop\SUVIVAL_GUEST_LECTURE.sas7bdat						*
*************************************************************************************************************;
/*PROC DATASETS LIBRARY=WORK KILL NOPRINT;QUIT;*/;
LIBNAME DESKTOP 'C:\Users\jrheintz\Desktop';




*************************************************************************************************************
* STEP 1: LOADING IN DATA
*************************************************************************************************************;
body, pre .CodeMirror, .log {
background-color #1e1e1e !important;
color #d4d4d4 !important;
}

PROC FORMAT;
VALUE GENDER 0='Female' 1='Male';
VALUE YESNO 0='No' 1='Yes' 9 ='Unknown';
VALUE RACE_2LEV 2='Other' 3='White';
VALUE ASA_2LEV 1='1 or 2' 3='3 or 4';
VALUE PJF 0='No PJF' 1='PJF';
VALUE PJK 0='No PJK' 1='PJK';
RUN;

DATA SUVIVAL_GUEST_LECTURE; SET '\\apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/suvival_guest_lecture';
FORMAT DOS PJF_date PJK_date DEATH_DATE FINAL_FOLLOW_DATE MMDDYY10.
	PJF PJF. PJK PJK.
	GENDER GENDER.
	RACE_2LEV RACE_2LEV.
	ASA_2LEV ASA_2LEV.
	Osteoporosis Osteopenia current_tobacco prior_hardware DEATH YESNO.
;
RUN;
PROC CONTENTS DATA=SUVIVAL_GUEST_LECTURE ORDER=VARNUM;RUN;
PROC PRINT DATA=SUVIVAL_GUEST_LECTURE (OBS=10);RUN;







*************************************************************************************************************
* STEP 2: SUMMARY STATS OF ALL VARIABLES
*************************************************************************************************************;
*OVERALL;
PROC FREQ DATA=SUVIVAL_GUEST_LECTURE;
TABLES PJF PJK DEATH GENDER RACE_2LEV ASA_2LEV Osteoporosis Osteopenia current_tobacco prior_hardware;
RUN;
PROC MEANS DATA=SUVIVAL_GUEST_LECTURE NOLABELS N NMISS MEAN STD MIN Q1 MEDIAN Q3 MAX;
VAR DAYS_PJF DAYS_PJF_ORCENSOR DAYS_PJK DAYS_PJK_ORCENSOR DAYS_PJK_TO_PJF DAYS_PJK_TO_PJF_ORCENSOR DAYS_DEATH DAYS_DEATH_ORCENSOR age bmi pre_sva pre_T1S pre_TK pre_LL pre_L1L4 pre_L4S1 pre_PI pre_PT pre_PILL HU_UIV;
RUN;

*BY PJF;
PROC FREQ DATA=SUVIVAL_GUEST_LECTURE;
TABLES DEATH*PJF GENDER*PJF RACE_2LEV*PJF ASA_2LEV*PJF Osteoporosis*PJF Osteopenia*PJF current_tobacco*PJF prior_hardware*PJF
	/ NOPERCENT EXPECTED CHISQ FISHER;
RUN;
PROC MEANS DATA=SUVIVAL_GUEST_LECTURE NOLABELS N NMISS MEAN STD MIN Q1 MEDIAN Q3 MAX;
VAR DAYS_PJF DAYS_PJF_ORCENSOR DAYS_PJK DAYS_PJK_ORCENSOR DAYS_PJK_TO_PJF DAYS_PJK_TO_PJF_ORCENSOR age bmi pre_sva pre_T1S pre_TK pre_LL pre_L1L4 pre_L4S1 pre_PI pre_PT pre_PILL HU_UIV;
CLASS PJF;
RUN;
PROC TTEST DATA=SUVIVAL_GUEST_LECTURE plots = none;
CLASS PJF; VAR DAYS_PJF DAYS_PJF_ORCENSOR DAYS_PJK DAYS_PJK_ORCENSOR DAYS_PJK_TO_PJF DAYS_PJK_TO_PJF_ORCENSOR age bmi pre_sva pre_T1S pre_TK pre_LL pre_L1L4 pre_L4S1 pre_PI pre_PT pre_PILL HU_UIV;
RUN; 



*BY PJK*;
PROC FREQ DATA=SUVIVAL_GUEST_LECTURE;
TABLES DEATH*PJK GENDER*PJK RACE_2LEV*PJK ASA_2LEV*PJK Osteoporosis*PJK Osteopenia*PJK current_tobacco*PJK prior_hardware*PJK
	/ NOPERCENT EXPECTED CHISQ FISHER;
RUN;

PROC MEANS DATA=SUVIVAL_GUEST_LECTURE NOLABELS N NMISS MEAN STD MIN Q1 MEDIAN Q3 MAX;
VAR DAYS_PJK DAYS_PJK_ORCENSOR DAYS_PJK DAYS_PJK_ORCENSOR DAYS_PJK_TO_PJF DAYS_PJK_TO_PJF_ORCENSOR age bmi pre_sva pre_T1S pre_TK pre_LL pre_L1L4 pre_L4S1 pre_PI pre_PT pre_PILL HU_UIV;
CLASS PJK;
RUN;
PROC TTEST DATA=SUVIVAL_GUEST_LECTURE;
CLASS PJK; VAR  DAYS_PJK DAYS_PJK_ORCENSOR DAYS_PJK_TO_PJK DAYS_PJK_TO_PJK_ORCENSOR age bmi pre_sva pre_T1S pre_TK pre_LL pre_L1L4 pre_L4S1 pre_PI pre_PT pre_PILL HU_UIV;
RUN; 

proc corr data = suvival_guest_lecture;
var PJK days_pjk days_pjk_orcensor age bmi pre_sva pre_t1s pre_TK pre_LL pre_L1L4 pre_l4s1 pre_pi pre_pill hu_UIV;
run;

*CREATING OUTPUT FOR INVESTIGATOR;
%MACRO CAT_TABLE(OUTCOME, VAR, DELETE=0, VAR_DISPLAY=0);
	PROC FREQ DATA=SUVIVAL_GUEST_LECTURE;
	TABLES &VAR.*&OUTCOME. 
		/ NOPERCENT EXPECTED CHISQ FISHER LIST OUT=&VAR._&OUTCOME._FREQ OUTPCT;
	ODS OUTPUT FishersExact=&VAR._&OUTCOME._FISH;
	WHERE &VAR. NE .;
	RUN;
	DATA &VAR._&OUTCOME. &VAR._NO&OUTCOME.; SET &VAR._&OUTCOME._FREQ;
	IF &VAR.=&DELETE. THEN DELETE;
	IF &OUTCOME.=1 THEN OUTPUT &VAR._&OUTCOME.;
	IF &OUTCOME.=0 THEN OUTPUT &VAR._NO&OUTCOME.;
	RUN;
	DATA &VAR._&OUTCOME.2; SET &VAR._&OUTCOME.;
	RENAME COUNT=COUNT_&OUTCOME.
		PCT_COL=PCT_COL_&OUTCOME.;
	DROP &VAR. PERCENT PCT_ROW;
	RUN;
	DATA &VAR._NO&OUTCOME.2; SET &VAR._NO&OUTCOME.;
	RENAME COUNT=COUNT_NO&OUTCOME.
		PCT_COL=PCT_COL_NO&OUTCOME.;
	DROP &VAR. PERCENT PCT_ROW;
	RUN;
	DATA &VAR._&OUTCOME._FISH2; SET &VAR._&OUTCOME._FISH;
	IF LABEL1="Two-sided Pr <= P";
	KEEP nValue1;
	RENAME nValue1=PVAL_FISH;
	RUN;
	%IF &VAR_DISPLAY = 0 %THEN %DO;
		DATA &VAR._&OUTCOME.; RETAIN VAR; MERGE &VAR._&OUTCOME.2 &VAR._NO&OUTCOME.2 &VAR._&OUTCOME._FISH2;
		VAR="&VAR.";
		RUN;
	%END;
	%ELSE %DO;
		DATA &VAR_DISPLAY._&OUTCOME.; RETAIN VAR; MERGE &VAR._&OUTCOME.2 &VAR._NO&OUTCOME.2 &VAR._&OUTCOME._FISH2;
		VAR="&VAR_DISPLAY.";
		RUN;
	%END;
		RUN;
/*	PROC PRINT DATA=&VAR._&OUTCOME.;RUN;*/
%MEND;


****STATS FOR PJF;
%CAT_TABLE(OUTCOME=PJF, VAR=DEATH);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=GENDER, VAR_DISPLAY=MALE);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=RACE_2LEV, DELETE=2, VAR_DISPLAY=WHITE);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=RACE_2LEV, DELETE=3, VAR_DISPLAY=NON_WHITE);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=ASA_2LEV, DELETE=3, VAR_DISPLAY=ASA_1_OR_2);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=ASA_2LEV, DELETE=1, VAR_DISPLAY=ASA_3_OR_4);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=Osteoporosis);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=Osteopenia);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=current_tobacco);RUN;
%CAT_TABLE(OUTCOME=PJF, VAR=prior_hardware);RUN;
DATA PJF_CAT_TABLE; LENGTH VAR $50;
SET DEATH_PJF MALE_PJF WHITE_PJF NON_WHITE_PJF ASA_1_OR_2_PJF ASA_3_OR_4_PJF Osteoporosis_PJF Osteopenia_PJF current_tobacco_PJF prior_hardware_PJF; RUN;
PROC PRINT DATA=PJF_CAT_TABLE; RUN;


****STATS FOR PJK;
%CAT_TABLE(OUTCOME=PJK, VAR=DEATH);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=GENDER, VAR_DISPLAY=MALE);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=RACE_2LEV, DELETE=2, VAR_DISPLAY=WHITE);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=RACE_2LEV, DELETE=3, VAR_DISPLAY=NON_WHITE);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=ASA_2LEV, DELETE=3, VAR_DISPLAY=ASA_1_OR_2);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=ASA_2LEV, DELETE=1, VAR_DISPLAY=ASA_3_OR_4);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=Osteoporosis);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=Osteopenia);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=current_tobacco);RUN;
%CAT_TABLE(OUTCOME=PJK, VAR=prior_hardware);RUN;
DATA PJK_CAT_TABLE; LENGTH VAR $50;
SET DEATH_PJK MALE_PJK WHITE_PJK NON_WHITE_PJK ASA_1_OR_2_PJK ASA_3_OR_4_PJK Osteoporosis_PJK Osteopenia_PJK current_tobacco_PJK prior_hardware_PJK; RUN;
PROC PRINT DATA=PJK_CAT_TABLE; RUN;



****STATS FOR DEATH;
%CAT_TABLE(OUTCOME=DEATH, VAR=GENDER, VAR_DISPLAY=MALE);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=RACE_2LEV, DELETE=2, VAR_DISPLAY=WHITE);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=RACE_2LEV, DELETE=3, VAR_DISPLAY=NON_WHITE);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=ASA_2LEV, DELETE=3, VAR_DISPLAY=ASA_1_OR_2);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=ASA_2LEV, DELETE=1, VAR_DISPLAY=ASA_3_OR_4);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=Osteoporosis);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=Osteopenia);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=current_tobacco);RUN;
%CAT_TABLE(OUTCOME=DEATH, VAR=prior_hardware);RUN;
DATA DEATH_CAT_TABLE; LENGTH VAR $50;
SET MALE_DEATH WHITE_DEATH NON_WHITE_DEATH ASA_1_OR_2_DEATH ASA_3_OR_4_DEATH Osteoporosis_DEATH Osteopenia_DEATH current_tobacco_DEATH prior_hardware_DEATH; RUN;
PROC PRINT DATA=DEATH_CAT_TABLE; RUN;









*************************************************************************************************************
* STEP 3: KM ANALYSIS
*************************************************************************************************************;
*****TIME TO PJF;
*RUN TEMPLATE TO MAKE PRETTY PLOT;
%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE FOR PJF.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_PJF;
	time DAYS_PJF_ORCENSOR*PJF(0);
run;


*****TIME TO PJK;
*RUN TEMPLATE TO MAKE PRETTY PLOT;
%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE FOR PJK.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_PJK;
	time DAYS_PJK_ORCENSOR*PJK(0);
run;
%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE PJK STRATIFY PJF.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_PJK_STRATA;
	time DAYS_PJK_ORCENSOR*PJK(0);
	STRATA PJF;
run;


*****TIME FROM PJK TO PJF;
*RUN TEMPLATE TO MAKE PRETTY PLOT;
%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE FOR PJK TO PJF.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_PJK_PJF;
	time DAYS_PJK_TO_PJF_ORCENSOR*PJF(0);
WHERE PJK=1 AND DAYS_PJK_TO_PJF_ORCENSOR>=0;
run;


*****TIME TO DEATH;
*RUN TEMPLATE TO MAKE PRETTY PLOT;
%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE FOR DEATH.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_DEATH;
	time DAYS_DEATH_ORCENSOR*DEATH(0);
run;

%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE DEATH STRATIFY PJF.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_DEATH;
	time DAYS_DEATH_ORCENSOR*DEATH(0);
	STRATA PJF;
run;

%include 'apporto.com\dfs\WCUPA\Users\dc1030974_wcupa\Desktop\Survival Analysis/KAPLAN MEIER TEMPLATE DEATH STRATIFY PJK.sas';
PROC LIFETEST DATA=SUVIVAL_GUEST_LECTURE plots=S (atrisk cl) OUTSURV=OUTSURV_DEATH;
	time DAYS_DEATH_ORCENSOR*DEATH(0);
	STRATA PJK;
run;







*************************************************************************************************************
* STEP 4: CHECKING PROPORTIONAL COX ASSUMPTIONS FOR UNIVARIATE MODELS OF PJF
*************************************************************************************************************;
****EXAMPLE OF MACRO;
proc phreg data=SUVIVAL_GUEST_LECTURE; 
MODEL DAYS_PJF_ORCENSOR*PJF(0) = age; 
ASSESS PH / RESAMPLE; 
output out=RES_age RESSCH=SCH_age RESDEV=DEV_age; 
ODS OUTPUT ProportionalHazardsSupTest=SUP_age; 
RUN;	
PROC CORR DATA=RES_age; 
VAR DAYS_PJF_ORCENSOR sch_age; 
ODS OUTPUT PearsonCorr=PC_age; 
RUN; 
DATA PC_age2; 
SET PC_age; 
RENAME SCH_age=CORR PSCH_age=PVAL; 
VAR='age'; KEEP VAR SCH_age PSCH_age;
IF INDEX(VARIABLE, 'DAYS'); 
RUN;	
proc phreg data=SUVIVAL_GUEST_LECTURE; 
MODEL DAYS_PJF_ORCENSOR*PJF(0) = age TIME_INT_age; 
TIME_INT_age=age*DAYS_PJF_ORCENSOR; 
ODS OUTPUT ParameterEstimates=PE_age; 
RUN; 
DATA PE_age2; 
SET  PE_age; 
IF PARAMETER='age' THEN DELETE; 
RUN;


*MACRO TO ASSESS ALL ASSUMPTIONS SIMULTANIOUSLY;
%MACRO COX_ASSUMPTIONS(OUTCOME, VAR);
	proc phreg data=SUVIVAL_GUEST_LECTURE; 
	CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
	MODEL DAYS_&OUTCOME._ORCENSOR*&OUTCOME.(0) = &VAR.; 
	ASSESS PH / RESAMPLE; 
	output out=RES_&VAR._&OUTCOME. RESSCH=SCH_&VAR. RESDEV=DEV_&VAR.; 
	ODS OUTPUT ProportionalHazardsSupTest=SUP_&VAR._&OUTCOME.; 
	RUN;	
	PROC CORR DATA=RES_&VAR._&OUTCOME.; 
	VAR DAYS_&OUTCOME._ORCENSOR sch_&VAR.; 
	ODS OUTPUT PearsonCorr=PC_&VAR._&OUTCOME.; 
	RUN; 
	DATA PC_&VAR._&OUTCOME.2; 
	SET PC_&VAR._&OUTCOME.; 
	RENAME SCH_&VAR.=CORR PSCH_&VAR.=PVAL; 
	VAR="&VAR."; KEEP VAR SCH_&VAR. PSCH_&VAR.;
	IF INDEX(VARIABLE, 'DAYS'); 
	RUN;	

	proc phreg data=SUVIVAL_GUEST_LECTURE;
	CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No"); 
	MODEL DAYS_&OUTCOME._ORCENSOR*&OUTCOME.(0) = &VAR. TIME_INT_&VAR.; 
	TIME_INT_&VAR.=&VAR.*DAYS_&OUTCOME._ORCENSOR; 
	ODS OUTPUT ParameterEstimates=PE_&VAR._&OUTCOME.; 
	RUN; 
	DATA PE_&VAR._&OUTCOME.2; 
	SET  PE_&VAR._&OUTCOME.; 
	IF PARAMETER="&VAR." THEN DELETE; 
	RUN;
%MEND;


****TESTING FOR PJF;
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=AGE);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=bmi);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_sva);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_T1S);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_TK);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_LL);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_L1L4);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_L4S1);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_PI);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_PT);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=pre_PILL);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=HU_UIV);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=GENDER);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=RACE_2LEV);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=ASA_2LEV);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=Osteoporosis);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=Osteopenia);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=current_tobacco);
%COX_ASSUMPTIONS(OUTCOME=PJF, VAR=prior_hardware);
DATA ALL_SUPS_PJF; LENGTH VARIABLE $50;
SET SUP_age_PJF SUP_bmi_PJF SUP_pre_sva_PJF SUP_pre_T1S_PJF SUP_pre_TK_PJF SUP_pre_LL_PJF SUP_pre_L1L4_PJF SUP_pre_L4S1_PJF SUP_pre_PI_PJF SUP_pre_PT_PJF SUP_pre_PILL_PJF SUP_HU_UIV_PJF SUP_GENDER_PJF SUP_RACE_2LEV_PJF SUP_ASA_2LEV_PJF SUP_Osteoporosis_PJF SUP_Osteopenia_PJF SUP_current_tobacco_PJF SUP_prior_hardware_PJF;
RUN;
DATA ALL_CORRS_PJF; LENGTH VAR $50;
SET PC_age_PJF2 PC_bmi_PJF2 PC_pre_sva_PJF2 PC_pre_T1S_PJF2 PC_pre_TK_PJF2 PC_pre_LL_PJF2 PC_pre_L1L4_PJF2 PC_pre_L4S1_PJF2 PC_pre_PI_PJF2 PC_pre_PT_PJF2 PC_pre_PILL_PJF2 PC_HU_UIV_PJF2 PC_GENDER_PJF2 PC_RACE_2LEV_PJF2 PC_ASA_2LEV_PJF2 PC_Osteoporosis_PJF2 PC_Osteopenia_PJF2 PC_current_tobacco_PJF2 PC_prior_hardware_PJF2;
RUN;
DATA ALL_TIME_INTS_PJF; LENGTH Parameter $50;
SET PE_age_PJF2 PE_bmi_PJF2 PE_pre_sva_PJF2 PE_pre_T1S_PJF2 PE_pre_TK_PJF2 PE_pre_LL_PJF2 PE_pre_L1L4_PJF2 PE_pre_L4S1_PJF2 PE_pre_PI_PJF2 PE_pre_PT_PJF2 PE_pre_PILL_PJF2 PE_HU_UIV_PJF2 PE_GENDER_PJF2 PE_RACE_2LEV_PJF2 PE_ASA_2LEV_PJF2 PE_Osteoporosis_PJF2 PE_Osteopenia_PJF2 PE_current_tobacco_PJF2 PE_prior_hardware_PJF2;
DROP LABEL; 
RUN;
PROC PRINT DATA=ALL_SUPS_PJF;RUN; *NONE;
PROC PRINT DATA=ALL_CORRS_PJF;RUN; *AGE, PRIOR_HARDWARE (MAYBE);
PROC PRINT DATA=ALL_TIME_INTS_PJF;RUN; *AGE;
*AGE TIME DEPENDENT!!!!!;


****TESTING FOR PJK;
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=AGE);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=bmi);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_sva);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_T1S);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_TK);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_LL);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_L1L4);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_L4S1);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_PI);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_PT);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=pre_PILL);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=HU_UIV);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=GENDER);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=RACE_2LEV);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=ASA_2LEV);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=Osteoporosis);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=Osteopenia);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=current_tobacco);
%COX_ASSUMPTIONS(OUTCOME=PJK, VAR=prior_hardware);
DATA ALL_SUPS_PJK; LENGTH VARIABLE $50;
SET SUP_age_PJK SUP_bmi_PJK SUP_pre_sva_PJK SUP_pre_T1S_PJK SUP_pre_TK_PJK SUP_pre_LL_PJK SUP_pre_L1L4_PJK SUP_pre_L4S1_PJK SUP_pre_PI_PJK SUP_pre_PT_PJK SUP_pre_PILL_PJK SUP_HU_UIV_PJK SUP_GENDER_PJK SUP_RACE_2LEV_PJK SUP_ASA_2LEV_PJK SUP_Osteoporosis_PJK SUP_Osteopenia_PJK SUP_current_tobacco_PJK SUP_prior_hardware_PJK;
RUN;
DATA ALL_CORRS_PJK; LENGTH VAR $50;
SET PC_age_PJK2 PC_bmi_PJK2 PC_pre_sva_PJK2 PC_pre_T1S_PJK2 PC_pre_TK_PJK2 PC_pre_LL_PJK2 PC_pre_L1L4_PJK2 PC_pre_L4S1_PJK2 PC_pre_PI_PJK2 PC_pre_PT_PJK2 PC_pre_PILL_PJK2 PC_HU_UIV_PJK2 PC_GENDER_PJK2 PC_RACE_2LEV_PJK2 PC_ASA_2LEV_PJK2 PC_Osteoporosis_PJK2 PC_Osteopenia_PJK2 PC_current_tobacco_PJK2 PC_prior_hardware_PJK2;
RUN;
DATA ALL_TIME_INTS_PJK; LENGTH Parameter $50;
SET PE_age_PJK2 PE_bmi_PJK2 PE_pre_sva_PJK2 PE_pre_T1S_PJK2 PE_pre_TK_PJK2 PE_pre_LL_PJK2 PE_pre_L1L4_PJK2 PE_pre_L4S1_PJK2 PE_pre_PI_PJK2 PE_pre_PT_PJK2 PE_pre_PILL_PJK2 PE_HU_UIV_PJK2 PE_GENDER_PJK2 PE_RACE_2LEV_PJK2 PE_ASA_2LEV_PJK2 PE_Osteoporosis_PJK2 PE_Osteopenia_PJK2 PE_current_tobacco_PJK2 PE_prior_hardware_PJK2;
DROP LABEL; 
RUN;
PROC PRINT DATA=ALL_SUPS_PJK;RUN; *GENDER;
PROC PRINT DATA=ALL_CORRS_PJK;RUN; *GENDER;
PROC PRINT DATA=ALL_TIME_INTS_PJK;RUN; *GENDER;
*GENDER TIME DEPENDENT!!!!!;


****TESTING FOR DEATH;
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=AGE);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=bmi);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_sva);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_T1S);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_TK);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_LL);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_L1L4);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_L4S1);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_PI);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_PT);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=pre_PILL);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=HU_UIV);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=GENDER);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=RACE_2LEV);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=ASA_2LEV);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=Osteoporosis);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=Osteopenia);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=current_tobacco);
%COX_ASSUMPTIONS(OUTCOME=DEATH, VAR=prior_hardware);
DATA ALL_SUPS_DEATH; LENGTH VARIABLE $50;
SET SUP_age_DEATH SUP_bmi_DEATH SUP_pre_sva_DEATH SUP_pre_T1S_DEATH SUP_pre_TK_DEATH SUP_pre_LL_DEATH SUP_pre_L1L4_DEATH SUP_pre_L4S1_DEATH SUP_pre_PI_DEATH SUP_pre_PT_DEATH SUP_pre_PILL_DEATH SUP_HU_UIV_DEATH SUP_GENDER_DEATH SUP_RACE_2LEV_DEATH SUP_ASA_2LEV_DEATH SUP_Osteoporosis_DEATH SUP_Osteopenia_DEATH SUP_current_tobacco_DEATH SUP_prior_hardware_DEATH;
RUN;
DATA ALL_CORRS_DEATH; LENGTH VAR $50;
SET PC_age_DEATH2 PC_bmi_DEATH2 PC_pre_sva_DEATH2 PC_pre_T1S_DEATH2 PC_pre_TK_DEATH2 PC_pre_LL_DEATH2 PC_pre_L1L4_DEATH2 PC_pre_L4S1_DEATH2 PC_pre_PI_DEATH2 PC_pre_PT_DEATH2 PC_pre_PILL_DEATH2 PC_HU_UIV_DEATH2 PC_GENDER_DEATH2 PC_RACE_2LEV_DEATH2 PC_ASA_2LEV_DEATH2 PC_Osteoporosis_DEATH2 PC_Osteopenia_DEATH2 PC_current_tobacco_DEATH2 PC_prior_hardware_DEATH2;
RUN;
DATA ALL_TIME_INTS_DEATH; LENGTH Parameter $50;
SET PE_age_DEATH2 PE_bmi_DEATH2 PE_pre_sva_DEATH2 PE_pre_T1S_DEATH2 PE_pre_TK_DEATH2 PE_pre_LL_DEATH2 PE_pre_L1L4_DEATH2 PE_pre_L4S1_DEATH2 PE_pre_PI_DEATH2 PE_pre_PT_DEATH2 PE_pre_PILL_DEATH2 PE_HU_UIV_DEATH2 PE_GENDER_DEATH2 PE_RACE_2LEV_DEATH2 PE_ASA_2LEV_DEATH2 PE_Osteoporosis_DEATH2 PE_Osteopenia_DEATH2 PE_current_tobacco_DEATH2 PE_prior_hardware_DEATH2;
DROP LABEL; 
RUN;
PROC PRINT DATA=ALL_SUPS_DEATH;RUN; *PRE_PI (MAYBE), PRE_PT (MAYBE);
PROC PRINT DATA=ALL_CORRS_DEATH;RUN; *PRE_PT (MAYBE),  OSTEOPOROSIS (MAYBE);
PROC PRINT DATA=ALL_TIME_INTS_DEATH;RUN; *PRE_PT (MAYBE) ASA (MAYBE), OSTEOPOROSIS (MAYBE);
*POSSIBLE TIME DEPENDENCE!!!!!;













*************************************************************************************************************
* STEP 5: PRODUCING OUTPUT OF PROPORTIONAL COX UNIVARIATE MODELS
*************************************************************************************************************;
* WRITE MACRO TO RUN FOR ALL VARIABLES;
proc phreg data=SUVIVAL_GUEST_LECTURE; 
CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
MODEL DAYS_PJF_ORCENSOR*PJF(0) = age; 
HAZARDRATIO age / CL=WALD DIFF=ref; 
ODS OUTPUT ParameterEstimates=PE_PJF_AGE HazardRatios=HR_PJF_AGE CensoredSummary=CS_PJF_AGE;
RUN;	
DATA PE_PJF_AGE2; SET PE_PJF_AGE; KEEP Parameter ProbChiSq; RUN;	
DATA HR_PJF_AGE2; SET HR_PJF_AGE; KEEP Description HazardRatio WaldLower WaldUpper ;RUN;	
DATA PE_HR_PJF_AGE; RETAIN OUTCOME PARAMETER; MERGE HR_PJF_AGE2 PE_PJF_AGE2; OUTCOME="PJF"; RUN;
DATA RS_VT_UNADJ; RETAIN OUTCOME Total Event Censored PARAMETER  ;
MERGE CS_PJF_AGE PE_HR_PJF_AGE; KEEP Total  Event Censored OUTCOME PARAMETER Description HazardRatio WaldLower WaldUpper ProbChiSq;
RUN;
PROC PRINT DATA=RS_VT_UNADJ;RUN;

*COX OUTPUT (NO TIME DEPENDENCE!!!);
%MACRO COX_OUTPUT(OUTCOME, VAR);
	proc phreg data=SUVIVAL_GUEST_LECTURE; 
	CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
	MODEL DAYS_&OUTCOME._ORCENSOR*&OUTCOME.(0) = &VAR.; 
	HAZARDRATIO &VAR. / CL=WALD DIFF=ref; 
	ODS OUTPUT ParameterEstimates=PE_&OUTCOME._&VAR. HazardRatios=HR_&OUTCOME._&VAR. CensoredSummary=CS_&OUTCOME._&VAR.;
	RUN;	
	DATA PE_&OUTCOME._&VAR.2; SET PE_&OUTCOME._&VAR.; KEEP Parameter ProbChiSq; RUN;	
	DATA HR_&OUTCOME._&VAR.2; SET HR_&OUTCOME._&VAR.; KEEP Description HazardRatio WaldLower WaldUpper ;RUN;	
	DATA PE_HR_&OUTCOME._&VAR.; RETAIN OUTCOME PARAMETER; MERGE HR_&OUTCOME._&VAR.2 PE_&OUTCOME._&VAR.2; OUTCOME="&OUTCOME."; RUN;
	DATA &OUTCOME._&VAR.; RETAIN OUTCOME Total Event Censored PARAMETER  ;
	MERGE CS_&OUTCOME._&VAR. PE_HR_&OUTCOME._&VAR.; KEEP Total  Event Censored OUTCOME PARAMETER Description HazardRatio WaldLower WaldUpper ProbChiSq;
	RUN;
	PROC PRINT DATA=&OUTCOME._&VAR.;RUN;
%MEND;


****MODELING PJF;
%COX_OUTPUT(OUTCOME=PJF, VAR=AGE);
%COX_OUTPUT(OUTCOME=PJF, VAR=bmi);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_sva);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_T1S);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_TK);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_LL);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_L1L4);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_L4S1);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_PI);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_PT);
%COX_OUTPUT(OUTCOME=PJF, VAR=pre_PILL);
%COX_OUTPUT(OUTCOME=PJF, VAR=HU_UIV);
%COX_OUTPUT(OUTCOME=PJF, VAR=GENDER);
%COX_OUTPUT(OUTCOME=PJF, VAR=RACE_2LEV);
%COX_OUTPUT(OUTCOME=PJF, VAR=ASA_2LEV);
%COX_OUTPUT(OUTCOME=PJF, VAR=Osteoporosis);
%COX_OUTPUT(OUTCOME=PJF, VAR=Osteopenia);
%COX_OUTPUT(OUTCOME=PJF, VAR=current_tobacco);
%COX_OUTPUT(OUTCOME=PJF, VAR=prior_hardware);
DATA COX_PJF; RETAIN OUTCOME Total Event Censored PARAMETER Description HazardRatio WaldLower WaldUpper ProbChiSq; LENGTH PARAMETER Description  $50;
SET PJF_age PJF_bmi PJF_pre_sva PJF_pre_T1S PJF_pre_TK PJF_pre_LL PJF_pre_L1L4 PJF_pre_L4S1 PJF_pre_PI PJF_pre_PT PJF_pre_PILL PJF_HU_UIV PJF_GENDER PJF_RACE_2LEV PJF_ASA_2LEV PJF_Osteoporosis PJF_Osteopenia PJF_current_tobacco PJF_prior_hardware;
RUN;
PROC PRINT DATA=COX_PJF; RUN;
proc phreg data=SUVIVAL_GUEST_LECTURE; 
CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
MODEL DAYS_PJF_ORCENSOR*PJF(0) = age TIME_INT_age; 
TIME_INT_age=age*DAYS_PJF_ORCENSOR; 
RUN;	


****MODELING PJK;
%COX_OUTPUT(OUTCOME=PJK, VAR=AGE);
%COX_OUTPUT(OUTCOME=PJK, VAR=bmi);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_sva);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_T1S);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_TK);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_LL);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_L1L4);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_L4S1);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_PI);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_PT);
%COX_OUTPUT(OUTCOME=PJK, VAR=pre_PILL);
%COX_OUTPUT(OUTCOME=PJK, VAR=HU_UIV);
%COX_OUTPUT(OUTCOME=PJK, VAR=GENDER);
%COX_OUTPUT(OUTCOME=PJK, VAR=RACE_2LEV);
%COX_OUTPUT(OUTCOME=PJK, VAR=ASA_2LEV);
%COX_OUTPUT(OUTCOME=PJK, VAR=Osteoporosis);
%COX_OUTPUT(OUTCOME=PJK, VAR=Osteopenia);
%COX_OUTPUT(OUTCOME=PJK, VAR=current_tobacco);
%COX_OUTPUT(OUTCOME=PJK, VAR=prior_hardware);
DATA COX_PJK; RETAIN OUTCOME Total Event Censored PARAMETER Description HazardRatio WaldLower WaldUpper ProbChiSq; LENGTH PARAMETER Description  $50;
SET PJK_age PJK_bmi PJK_pre_sva PJK_pre_T1S PJK_pre_TK PJK_pre_LL PJK_pre_L1L4 PJK_pre_L4S1 PJK_pre_PI PJK_pre_PT PJK_pre_PILL PJK_HU_UIV PJK_GENDER PJK_RACE_2LEV PJK_ASA_2LEV PJK_Osteoporosis PJK_Osteopenia PJK_current_tobacco PJK_prior_hardware;
RUN;
PROC PRINT DATA=COX_PJK; RUN;
proc phreg data=SUVIVAL_GUEST_LECTURE; 
CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
MODEL DAYS_PJK_ORCENSOR*PJK(0) = GENDER TIME_INT_GENDER; 
TIME_INT_GENDER=GENDER*DAYS_PJK_ORCENSOR; 
RUN;	


****MODELING DEATH;
%COX_OUTPUT(OUTCOME=DEATH, VAR=AGE);
%COX_OUTPUT(OUTCOME=DEATH, VAR=bmi);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_sva);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_T1S);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_TK);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_LL);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_L1L4);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_L4S1);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_PI);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_PT);
%COX_OUTPUT(OUTCOME=DEATH, VAR=pre_PILL);
%COX_OUTPUT(OUTCOME=DEATH, VAR=HU_UIV);
%COX_OUTPUT(OUTCOME=DEATH, VAR=GENDER);
%COX_OUTPUT(OUTCOME=DEATH, VAR=RACE_2LEV);
%COX_OUTPUT(OUTCOME=DEATH, VAR=ASA_2LEV);
%COX_OUTPUT(OUTCOME=DEATH, VAR=Osteoporosis);
%COX_OUTPUT(OUTCOME=DEATH, VAR=Osteopenia);
%COX_OUTPUT(OUTCOME=DEATH, VAR=current_tobacco);
%COX_OUTPUT(OUTCOME=DEATH, VAR=prior_hardware);
DATA COX_DEATH; RETAIN OUTCOME Total Event Censored PARAMETER Description HazardRatio WaldLower WaldUpper ProbChiSq; LENGTH PARAMETER Description  $50;
SET DEATH_age DEATH_bmi DEATH_pre_sva DEATH_pre_T1S DEATH_pre_TK DEATH_pre_LL DEATH_pre_L1L4 DEATH_pre_L4S1 DEATH_pre_PI DEATH_pre_PT DEATH_pre_PILL DEATH_HU_UIV DEATH_GENDER DEATH_RACE_2LEV DEATH_ASA_2LEV DEATH_Osteoporosis DEATH_Osteopenia DEATH_current_tobacco DEATH_prior_hardware;
RUN;
PROC PRINT DATA=COX_DEATH; RUN;
proc phreg data=SUVIVAL_GUEST_LECTURE; 
CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
MODEL DAYS_DEATH_ORCENSOR*DEATH(0) = PRE_PT TIME_INT_PRE_PT;
TIME_INT_PRE_PT=PRE_PT*DAYS_DEATH_ORCENSOR; 
RUN;	
proc phreg data=SUVIVAL_GUEST_LECTURE; 
CLASS GENDER(REF="Female") RACE_2LEV(REF="Other") ASA_2LEV(Ref="1 or 2") Osteoporosis(REF="No") Osteopenia(REF="No") current_tobacco(REF="No") prior_hardware(REF="No");
MODEL DAYS_DEATH_ORCENSOR*DEATH(0) = Osteoporosis TIME_INT_Osteoporosis;
TIME_INT_Osteoporosis=Osteoporosis*DAYS_DEATH_ORCENSOR; 
RUN;	









*************************************************************************************************************
* STEP 6: FINE-GRAY 
*************************************************************************************************************;
* WRITE MACRO TO RUN FOR ALL VARIABLES;
****EXAMPLE OF MACRO;









*************************************************************************************************************
* STEP 7: PRODUCING IPW FOR PJK AND RERUNNING STEPS 2-6 
*************************************************************************************************************;


